dist: trusty
language: python
python:
  - 2.7
  - 3.6

notifications:
  email: false

install:
  - pip install tox-travis
  - mkdir ~/.aws
  - printf "[default]\nregion = us-east-1\n[profile no-region]" > ~/.aws/config
  - cp .ecstools.example ~/.ecstools

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  user: boroivanov
  password: $PYPI_PASS
  on:
    tags: true
    repo: boroivanov/ecs-tools
