dist: xenial
language: python
python: 3.7

notifications:
  email: false

install:
  - pip install tox-travis
  - mkdir ~/.aws
  - printf "[default]\nregion = us-east-1\n[profile no-region]" > ~/.aws/config

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  user: boroivanov
  password: $PYPI_PASS
  on:
    tags: true
    repo: boroivanov/ecs-tools
