dist: xenial
language: python
python: 3.7

notifications:
  email: false

install:
  - pip install tox-travis
  - pip install -r requirements-test.txt
  - mkdir ~/.aws
  - printf "[default]\nregion = us-east-1\n[profile no-region]" > ~/.aws/config
  - printf "[default]\naws_access_key_id=XXXXXXXXXXXXXX\naws_secret_access_key=YYYYYYYYYYYYYYYYYYYYYYYYYYY\n" > ~/.aws/credentials

before_script:
  - sudo rm -f /etc/boto.cfg # https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-310759657
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - echo tests go here
  # - python -m pytest --cov-report term-missing --cov ecstools --cov-report xml
  # - python -m flake8 ecstools

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  user: boroivanov
  password: $PYPI_PASS
  on:
    tags: true
    repo: boroivanov/ecs-tools
